# Replace with your Discord Application ID
application_id: "1508172253085307021"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 0

# Activity Details
name: "Animation71"
details: "@ 100.0%"
state: ""

# Activity Images
largeImageKey: "1508172253085307021"
largeImageText: "Untitled"
smallImageKey: ""
smallImageText: ""

# Activity URL (optional, works only with certain types)
url: ""

# Activity Buttons (optional)
# أزلنا الأزرار لأن الألعاب الأصلية على الديسكورد لا تحتوي على أزرار روابط
buttons: []

# Activity Custom status
custom_status: ""
custom_emoji: ""
